# MariaDB Configuration
spring.datasource.url=jdbc:mariadb://localhost:3306/alltix_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=HumF5&Bv
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver


# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDB103Dialect
spring.jpa.properties.hibernate.format_sql=true

# Server Configuration
server.port=8080

# Thymeleaf Configuration
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.servlet.content-type=text/html
spring.thymeleaf.cache=false

# Static Resources
spring.web.resources.static-locations=classpath:/static/

# Date/Time Format
spring.mvc.format.date-time=yyyy-MM-dd HH:mm:ss
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=UTC